import { PageHeader } from "~/layouts/components/page-header"
import { PageContainer } from "~/layouts/components/page-container"
import { DataTable } from "~/components/data-table"
import { Link } from "react-router"
import {
  eventColumns,
  type EventTableRow,
} from "../../components/data-table/helpers/events-table"

{
  /* TODO: remove this --- START */
}
const mockData: EventTableRow[] = [
  {
    id: 1,
    header: "Opening & Welkomstwoord",
    type: "Executive Summary",
    status: "Done",
    target: "250",
    limit: "300",
    reviewer: "Eddie Lake",
  },
  {
    id: 2,
    header: "Locatie & Logistiek",
    type: "Technical Approach",
    status: "In Progress",
    target: "120",
    limit: "180",
    reviewer: "Assign reviewer",
  },
  {
    id: 3,
    header: "Sprekerslijn",
    type: "Capabilities",
    status: "Done",
    target: "80",
    limit: "120",
    reviewer: "Jamik Tashpulatov",
  },
  {
    id: 4,
    header: "Partner Presentaties",
    type: "Narrative",
    status: "Not Started",
    target: "200",
    limit: "260",
    reviewer: "Assign reviewer",
  },
  {
    id: 5,
    header: "Afsluiting & Netwerkborrel",
    type: "Focus Documents",
    status: "In Progress",
    target: "140",
    limit: "180",
    reviewer: "Emily Whalen",
  },
  {
    id: 6,
    header: "Registratie & Badge-uitgifte",
    type: "Operational",
    status: "Done",
    target: "300",
    limit: "350",
    reviewer: "Michael Chen",
  },
  {
    id: 7,
    header: "Catering Logistiek",
    type: "Technical Approach",
    status: "In Progress",
    target: "150",
    limit: "200",
    reviewer: "Assign reviewer",
  },
  {
    id: 8,
    header: "Keynote: Innovatie",
    type: "Narrative",
    status: "Not Started",
    target: "450",
    limit: "500",
    reviewer: "Sophia Rodriguez",
  },
  {
    id: 9,
    header: "Break-out Sessie 1",
    type: "Capabilities",
    status: "Done",
    target: "100",
    limit: "150",
    reviewer: "Lars van der Berg",
  },
  {
    id: 10,
    header: "Netwerk Lunch",
    type: "Focus Documents",
    status: "Done",
    target: "250",
    limit: "300",
    reviewer: "Emily Whalen",
  },
  {
    id: 11,
    header: "Sponsor Expo",
    type: "Executive Summary",
    status: "In Progress",
    target: "400",
    limit: "450",
    reviewer: "Eddie Lake",
  },
  {
    id: 12,
    header: "Workshop: AI Trends",
    type: "Technical Approach",
    status: "Not Started",
    target: "60",
    limit: "100",
    reviewer: "Assign reviewer",
  },
  {
    id: 13,
    header: "Paneldiscussie Fintech",
    type: "Narrative",
    status: "Done",
    target: "180",
    limit: "220",
    reviewer: "Jamik Tashpulatov",
  },
  {
    id: 14,
    header: "Koffiepauze Middag",
    type: "Operational",
    status: "Done",
    target: "120",
    limit: "150",
    reviewer: "Michael Chen",
  },
  {
    id: 15,
    header: "Product Lancering",
    type: "Capabilities",
    status: "In Progress",
    target: "500",
    limit: "600",
    reviewer: "Sophia Rodriguez",
  },
  {
    id: 16,
    header: "VIP Diner",
    type: "Focus Documents",
    status: "Not Started",
    target: "50",
    limit: "80",
    reviewer: "Assign reviewer",
  },
  {
    id: 17,
    header: "Vervoersplan VIPs",
    type: "Technical Approach",
    status: "Done",
    target: "90",
    limit: "120",
    reviewer: "Lars van der Berg",
  },
  {
    id: 18,
    header: "Beveiligingsplan",
    type: "Risk Assessment",
    status: "Done",
    target: "300",
    limit: "300",
    reviewer: "Eddie Lake",
  },
  {
    id: 19,
    header: "Branding & Signage",
    type: "Narrative",
    status: "In Progress",
    target: "220",
    limit: "280",
    reviewer: "Emily Whalen",
  },
  {
    id: 20,
    header: "AV & Lichtplan",
    type: "Technical Approach",
    status: "Not Started",
    target: "180",
    limit: "250",
    reviewer: "Assign reviewer",
  },
  {
    id: 21,
    header: "Social Media Campagne",
    type: "Marketing",
    status: "Done",
    target: "400",
    limit: "500",
    reviewer: "Sophia Rodriguez",
  },
  {
    id: 22,
    header: "Website Update",
    type: "Technical Approach",
    status: "In Progress",
    target: "110",
    limit: "150",
    reviewer: "Michael Chen",
  },
  {
    id: 23,
    header: "Pers uitnodigingen",
    type: "Narrative",
    status: "Not Started",
    target: "150",
    limit: "200",
    reviewer: "Jamik Tashpulatov",
  },
  {
    id: 24,
    header: "Budget Goedkeuring",
    type: "Executive Summary",
    status: "Done",
    target: "100",
    limit: "100",
    reviewer: "Eddie Lake",
  },
  {
    id: 25,
    header: "Locatie Inspectie",
    type: "Operational",
    status: "Done",
    target: "140",
    limit: "160",
    reviewer: "Lars van der Berg",
  },
  {
    id: 26,
    header: "EHBO Protocol",
    type: "Risk Assessment",
    status: "In Progress",
    target: "80",
    limit: "100",
    reviewer: "Assign reviewer",
  },
  {
    id: 27,
    header: "Duurzaamheidsplan",
    type: "Focus Documents",
    status: "Not Started",
    target: "200",
    limit: "250",
    reviewer: "Emily Whalen",
  },
  {
    id: 28,
    header: "Vrijwilligers Planning",
    type: "Capabilities",
    status: "Done",
    target: "120",
    limit: "180",
    reviewer: "Michael Chen",
  },
  {
    id: 29,
    header: "Gadget Inkoop",
    type: "Operational",
    status: "In Progress",
    target: "300",
    limit: "400",
    reviewer: "Assign reviewer",
  },
  {
    id: 30,
    header: "Fotografie Briefing",
    type: "Narrative",
    status: "Not Started",
    target: "90",
    limit: "120",
    reviewer: "Sophia Rodriguez",
  },
  {
    id: 31,
    header: "Video Registratie",
    type: "Technical Approach",
    status: "Done",
    target: "400",
    limit: "500",
    reviewer: "Jamik Tashpulatov",
  },
  {
    id: 32,
    header: "Spreker Briefing",
    type: "Capabilities",
    status: "In Progress",
    target: "110",
    limit: "140",
    reviewer: "Eddie Lake",
  },
  {
    id: 33,
    header: "Hotel Boekingen",
    type: "Operational",
    status: "Not Started",
    target: "250",
    limit: "300",
    reviewer: "Assign reviewer",
  },
  {
    id: 34,
    header: "Ticketverkoop Analyse",
    type: "Executive Summary",
    status: "Done",
    target: "500",
    limit: "500",
    reviewer: "Emily Whalen",
  },
  {
    id: 35,
    header: "Parkeer Coördinatie",
    type: "Technical Approach",
    status: "In Progress",
    target: "140",
    limit: "200",
    reviewer: "Lars van der Berg",
  },
  {
    id: 36,
    header: "Podium Techniek",
    type: "Technical Approach",
    status: "Not Started",
    target: "160",
    limit: "200",
    reviewer: "Assign reviewer",
  },
  {
    id: 37,
    header: "Backstage Catering",
    type: "Operational",
    status: "Done",
    target: "70",
    limit: "100",
    reviewer: "Michael Chen",
  },
  {
    id: 38,
    header: "Vertalingen (Simultaan)",
    type: "Capabilities",
    status: "In Progress",
    target: "190",
    limit: "240",
    reviewer: "Sophia Rodriguez",
  },
  {
    id: 39,
    header: "Enquête Ontwerp",
    type: "Focus Documents",
    status: "Not Started",
    target: "100",
    limit: "150",
    reviewer: "Jamik Tashpulatov",
  },
  {
    id: 40,
    header: "Bedankkaarten Sponsors",
    type: "Narrative",
    status: "Done",
    target: "130",
    limit: "180",
    reviewer: "Eddie Lake",
  },
  {
    id: 41,
    header: "Financiële Afsluiting",
    type: "Executive Summary",
    status: "In Progress",
    target: "300",
    limit: "350",
    reviewer: "Assign reviewer",
  },
  {
    id: 42,
    header: "Debriefing Team",
    type: "Operational",
    status: "Not Started",
    target: "80",
    limit: "120",
    reviewer: "Lars van der Berg",
  },
  {
    id: 43,
    header: "Marketing ROI Rapport",
    type: "Narrative",
    status: "Done",
    target: "240",
    limit: "300",
    reviewer: "Emily Whalen",
  },
  {
    id: 44,
    header: "Follow-up Mails",
    type: "Focus Documents",
    status: "In Progress",
    target: "150",
    limit: "200",
    reviewer: "Michael Chen",
  },
  {
    id: 45,
    header: "Opslag Materiaal",
    type: "Operational",
    status: "Not Started",
    target: "100",
    limit: "150",
    reviewer: "Assign reviewer",
  },
  {
    id: 46,
    header: "Vergunningsaanvraag",
    type: "Risk Assessment",
    status: "Done",
    target: "50",
    limit: "50",
    reviewer: "Eddie Lake",
  },
  {
    id: 47,
    header: "Schoonmaak Plan",
    type: "Operational",
    status: "In Progress",
    target: "120",
    limit: "160",
    reviewer: "Lars van der Berg",
  },
  {
    id: 48,
    header: "Gastenlijst Management",
    type: "Capabilities",
    status: "Done",
    target: "400",
    limit: "450",
    reviewer: "Sophia Rodriguez",
  },
  {
    id: 49,
    header: "Wi-Fi Capaciteit Test",
    type: "Technical Approach",
    status: "In Progress",
    target: "200",
    limit: "250",
    reviewer: "Assign reviewer",
  },
  {
    id: 50,
    header: "Slot Presentatie",
    type: "Executive Summary",
    status: "Not Started",
    target: "180",
    limit: "220",
    reviewer: "Jamik Tashpulatov",
  },
]
{
  /* TODO: remove this --- END */
}

export default function Page() {
  return (
    <>
      <PageHeader title="Evenementen" />
      <PageContainer>
        <h2>Evenementen</h2>

        {/* TODO: remove this --- START */}
        <div className="mt-6">
          <DataTable
            data={mockData}
            columns={eventColumns}
            filterColumnId="header"
            filterPlaceholder="Filter op naam..."
            getRowId={(row) => row.id.toString()}
          />
        </div>
        {/* TODO: remove this --- END */}
      </PageContainer>
    </>
  )
}
