@Backend.Web_HostAddress = http://localhost:5283

POST {{Backend.Web_HostAddress}}/api/todos
Content-Type: application/json
Accept: application/json

{
  "title": "Setup vertical slice architecture",
  "description": "Use request handlers and validation"
}

###

@todoId = 00000000-0000-0000-0000-000000000000
GET {{Backend.Web_HostAddress}}/api/todos/{{todoId}}
Accept: application/json

###
