// This file is auto-generated by Backend.Web/Scripts/Sync-FrontendTypes.ps1.
// Do not edit manually.

import type { EventRo } from './generated-types/event-ro'
import type { EventStyleRo } from './generated-types/event-style-ro'
import type { CreateEventDto } from './generated-types/create-event-dto'
import type { CreateEventStyleDto } from './generated-types/create-event-style-dto'
import type { UpdateEventDto } from './generated-types/update-event-dto'
import type { UpdateEventStyleDto } from './generated-types/update-event-style-dto'
import type { SessionRo } from './generated-types/session-ro'
import type { SessionRoomRo } from './generated-types/session-room-ro'
import type { CreateSessionDto } from './generated-types/create-session-dto'
import type { UpdateSessionDto } from './generated-types/update-session-dto'
import type { RoomRo } from './generated-types/room-ro'
import type { CreateRoomDto } from './generated-types/create-room-dto'
import type { UpdateRoomDto } from './generated-types/update-room-dto'

export type Event = EventRo
export type EventStyle = EventStyleRo
export type Session = SessionRo
export type SessionRoom = SessionRoomRo
export type Room = RoomRo

export type CreateEvent = CreateEventDto
export type CreateEventStyle = CreateEventStyleDto
export type CreateSession = CreateSessionDto
export type CreateRoom = CreateRoomDto

export type UpdateEvent = UpdateEventDto
export type UpdateEventStyle = UpdateEventStyleDto
export type UpdateSession = UpdateSessionDto
export type UpdateRoom = UpdateRoomDto