<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Backend.Common\Backend.Common.csproj" />
        <ProjectReference Include="..\Backend.Domain\Backend.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="FluentValidation" Version="12.1.0" />
        <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.0" />
        <PackageReference Include="MediatR" Version="13.1.0" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.0" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Features\Sessions\Handlers\" />
      <Folder Include="Features\Sessions\Repositories\" />
      <Folder Include="Features\Sessions\Requests\" />
      <Folder Include="Features\Sessions\Responses\" />
      <Folder Include="Features\Sessions\Validators\" />
    </ItemGroup>

</Project>
